<?php
echo '<html>';
echo '<head>';
echo '<title>';
echo 'Registration Page';
echo '</title>';
echo '</head>';
echo '<body bgcolor="Lightskyblue">';
echo '';
echo '<img src="https://www.auf.edu.ph/home/images/logo2.png" />';
echo '<hr />';
echo '';
echo '<form action="target.php" method="POST">';
echo '<label> First Name </label>';
echo '<input type="text" name="firstname" size="15"/>';
echo '<label> Middle Name: </label>';
echo '<input type="text" name="middlename" size="15"/>';
echo '<label> Last Name: </label>';
echo '<input type="text" name="lastname" size="15"/> <br> <br>';
echo 'Email:';
echo '<input type="email" name="email"/>';
echo '';
echo '<label>Phone:</label>';
echo '<input type="text" name="country code"  value="+63" size="2"/>';
echo '<input type="number" name="phone_number" size="10"/> <br> <br>';
echo '';
echo '<label>Sex:</label><br>';
echo '<input type="radio" name="sex" value="male" checked="checked" /> Male <br>';
echo '<input type="radio" name="sex" value="female" /> Female';
echo '<br>  <br>';
echo 'Birthdate:';
echo '<input type="date" name="birthdate"/> <br>';
echo '<br>';
echo '';
echo '<label>Program:</label>';
echo '<select name="program">';
echo '<option value="BSA">BS Accountancy</option>';
echo '<option value="BSBA">BS Business Administration</option>';
echo '<option value="BSEE">BS Electronics Engineering</option>';
echo '<option value="BSIT">BS Information Technology</option>';
echo '<option value="BSCS">BS Computer Science</option>';
echo '</select>';
echo '';
echo '<br>';
echo '<br>';
echo '';
echo 'Address';
echo '<br>';
echo '<textarea cols="80" rows="5" name="address"></textarea>';
echo '<br> <br>';
echo '';
echo '<input type="submit" value="Register Now"/>';
echo '</form>';
echo '';
echo '</body>';
echo '</html>';
?>
